Add subheader option to sidebar
saleor/macaw-ui pull request #106
Opened 2022-01-19 16:08 UTC by orzechdev

<img width="312" alt="Zrzut ekranu 2022-01-19 o 12 44 31" src="https://user-images.githubusercontent.com/9825562/150169352-2653eaf6-cc85-4729-a0f0-a3ceed2050de.png">
<img width="284" alt="Zrzut ekranu 2022-01-19 o 12 49 22" src="https://user-images.githubusercontent.com/9825562/150169360-fe7e6ef5-b7f7-4fb2-b690-7b9a0a66792a.png">

2022-01-19 16:08 UTC, patrys commented
Task linked: [SALEOR-4918 Extend dashboard navigation to support Apps](https://app.clickup.com/t/2549495/SALEOR-4918)

2022-01-20 12:41 UTC, Droniu approved these changes

2022-01-20 12:41 UTC, Droniu commented on src/SidebarDrawer/SidebarDrawer.tsx
> +                      </Typography>
This might need `key` prop too

2022-01-21 09:22 UTC, dominik-zeglen requested changes
I'm kinda starting to regret that I didn't refactor this to compound component pattern but it is what it is 🤷‍♂️

Instead of creating whole new type, maybe we can make `url` optional and use it to differentiate menu items from section headers?
Or, preferably but I guess nobody has time for that, refactor it to make `<Sidebar />` get children instead of `menuStructure` prop?

2022-01-26 08:30 UTC, dominik-zeglen approved these changes

2022-01-26 08:32 UTC, merged