Add circle indicator icons
saleor/macaw-ui pull request #116
Opened 2022-02-13 10:54 UTC by Droniu

I want to merge this change because it adds circle indicator icons (required for fulfillment creation refactor in the dashboard):
![image](https://user-images.githubusercontent.com/41952692/153749844-93c0847f-40cb-4a9b-974a-ec9c8b67f9e8.png)

2022-02-14 08:17 UTC, Cloud11PL commented on src/icons/ErrorCircleIndicatorIcon.tsx
> +(ErrorCircleIndicatorIcon as React.ComponentType).defaultProps = {
Why not use typescript interface for `viewBox` instead of `defaultProps`? I see that it's used in some icons so it can be reused.

2022-02-15 09:24 UTC, dominik-zeglen requested changes
It'd be better to add colorless empty and with success mark variants. This way we'll be able to change its colors without having to edit svg markup directly. Also colors will probably differ for dark mode anyway.

2022-02-17 10:10 UTC, patrys commented
Task linked: [SALEOR-4789 Add warehouse selection button on Unfulfilled Card](https://app.clickup.com/t/2549495/SALEOR-4789)

2022-02-17 13:55 UTC, Cloud11PL approved these changes

2022-02-24 09:51 UTC, dominik-zeglen approved these changes

2022-02-24 09:52 UTC, merged