Update icons
saleor/macaw-ui pull request #143
Opened 2022-05-04 11:55 UTC by witoszekdev

I want to merge this becasue it updates the icons to the new design and adds new icon generation script from SVGR

2022-05-04 11:55 UTC, patrys commented
Task linked: [SALEOR-6758 Icons](https://app.clickup.com/t/2549495/SALEOR-6758)

2022-05-10 09:06 UTC, dominik-zeglen commented
Caught some artifacts:
<img width="166" alt="Zrzut ekranu 2022-05-10 o 11 06 16" src="https://user-images.githubusercontent.com/6833443/167592381-f339a219-0bf3-4f21-998b-ef734c391bdf.png">
<img width="342" alt="Zrzut ekranu 2022-05-10 o 11 06 11" src="https://user-images.githubusercontent.com/6833443/167592386-f94d31b2-319d-40d8-a069-4a43d317c8d3.png">
<img width="98" alt="Zrzut ekranu 2022-05-10 o 11 06 09" src="https://user-images.githubusercontent.com/6833443/167592389-a4cf0287-d829-406a-9168-f0f9f799b8df.png">
<img width="371" alt="Zrzut ekranu 2022-05-10 o 11 05 56" src="https://user-images.githubusercontent.com/6833443/167592392-50ecb1aa-86e8-4017-8fdf-e72713d9310f.png">
<img width="136" alt="Zrzut ekranu 2022-05-10 o 11 05 48" src="https://user-images.githubusercontent.com/6833443/167592398-438cf5f3-dab1-4af3-89ee-ea4ffc540c9d.png">

2022-05-11 07:28 UTC, dominik-zeglen approved these changes

2022-05-11 07:31 UTC, dominik-zeglen requested changes
Stories are missing icons

<img width="849" alt="Zrzut ekranu 2022-05-11 o 09 30 08" src="https://user-images.githubusercontent.com/6833443/167793632-5dbc32b6-9314-44cd-b520-a59acfa663c8.png">

2022-05-13 08:41 UTC, dominik-zeglen approved these changes

2022-05-13 09:59 UTC, merged