feat: infinity scroll for dynami multiselect and combobox
saleor/macaw-ui pull request #565
Opened 2023-09-05 14:46 UTC by poulch

I want to merge this change because it adds infnifty scroll feature for both dynamic inputs

This PR closes #...

### Screenshots

### Pull Request Checklist

- [ ] New components are exported from `./src/components/index.ts`.
- [ ] The storybook story is created and documentation is properly generated.
- [ ] New component is wrapped in `forwardRef`.

2023-09-06 07:02 UTC, andrzejewsky requested changes

2023-09-06 07:02 UTC, andrzejewsky commented on src/hooks/useInfnityScroll.ts
> +    const observer = new IntersectionObserver(
**issue**: that means you create new instance on each render, without cleaning it - i expect memory leak here. If you create a new instance, first you need to clean previous one

2023-09-06 10:44 UTC, krzysztofzuraw approved these changes

2023-09-06 13:47 UTC, krzysztofzuraw commented on src/hooks/useInfnityScroll.ts
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
**Question:** shouldn't this comment be on line 38?

2023-09-06 14:03 UTC, krzysztofzuraw submitted a review, later dismissed

2023-09-07 06:30 UTC, krzysztofzuraw approved these changes

2023-09-07 07:28 UTC, andrzejewsky approved these changes

2023-09-07 07:31 UTC, merged