Export radio indicator
saleor/macaw-ui pull request #768
Opened 2024-03-06 13:08 UTC by Droniu

I want to merge this change because it exports radio indicator, allowing for custom radio group implementations - right now we need radio tiles in the dashboard.

### Screenshots

### Pull Request Checklist

- [x] New components are exported from `./src/components/index.ts`.
- [ ] The storybook story is created and documentation is properly generated.
- [x] New component is wrapped in `forwardRef`.

2024-03-06 13:42 UTC, poulch approved these changes

2024-03-11 10:33 UTC, krzysztofzuraw requested changes

2024-03-11 10:33 UTC, krzysztofzuraw commented on src/components/RadioGroup/Indicator.tsx
> +>(({ disabled, asChild }, ref) => {
**Question:** Won't types be wrong here?

I mean you can use any type from `Box` but we need to spread the rest of `...props` on svg component 🤔

2024-03-11 14:44 UTC, krzysztofzuraw approved these changes

2024-03-15 10:39 UTC, poulch approved these changes

2024-03-15 10:45 UTC, merged